INPUT:
  FORMAT: "RGB"

MODEL:
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  META_ARCHITECTURE: "VQVAEModel"
  INIT_TYPE: "xavier_uniform"
  ENCODER:
    NAME: "ResEncoder"
    N_LAYERS: 2
    NF: 256
    OUT_CHANNELS: 256
    RES_CHANNELS: 128
    NORM: ""
    IN_CHANNELS: 3
    WEIGHTS: "/private/home/homanga/affordance/affordance_code/models/vqvae_best/netE/model_final.pth"
  GENERATOR:
    NAME: "ResDecoder"
    N_LAYERS: 2
    IN_CHANNELS: 256
    RES_CHANNELS: 128
    NF: 256
    NORM: ""
    OUT_CHANNELS: 3
    OUT_ACTIVATION: "tanh"
    WEIGHTS: "/private/home/homanga/affordance/affordance_code/models/vqvae_best/netG/model_final.pth"
  CODEBOOK:
    SIZE: 512
    DIM: 256
    EMA: True
    NUM: 4
    WEIGHTS: "/private/home/homanga/affordance/affordance_code/models/vqvae_best/netC/model_final.pth"
SOLVER:
  IMS_PER_BATCH: 64
  MAX_ITER: 500000
  LR_G: 0.0003
  LR_SCHEDULER_NAME: "Identity"
  CHECKPOINT_PERIOD: 10000
VERSION: 1
SEED: 123456
TEST:
  EVALUATORS: "MSEEvaluator,CodesExtractor"
DATASETS:
  TRAIN: ("final_train",) 
  TEST: ("final_test_seq",) 
